<?php

namespace common\models;

use Yii;
use yii\alexposseda\fileManager\FileManager;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "{{%option}}".
 *
 * @property integer $id
 * @property string $name
 * @property string $price
 * @property string $icon
 * @property string $description
 * @property integer $stock
 * @property integer $created_at
 * @property integer $updated_at
 */
class Option extends ActiveRecord
{
    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
        $icon = json_decode($this->icon);
        if (!empty($icon)) {
            FileManager::getInstance()
                ->removeFromSession($icon[0]);
        }
    }

    public function getIcon()
    {
        $icon = json_decode($this->icon);
        return FileManager::getInstance()->getStorageUrl() . (!empty($icon[0]) ? $icon[0] : 'no_image.jpg');
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%option}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'price', 'description'], 'required'],
            [['price'], 'number'],
            [['description'], 'string'],
            [['stock', 'created_at', 'updated_at'], 'integer'],
            [['name', 'icon'], 'string', 'max' => 255],
            [['name'], 'unique'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'price' => 'Price',
            'icon' => 'Icon',
            'description' => 'Description',
            'stock' => 'Stock',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }
}
