<?php
namespace common\models\traits;


use yii\alexposseda\fileManager\FileManager;

trait iconTrait
{
    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
        $icon = json_decode($this->icon);
        if(!empty($icon)){
            FileManager::getInstance()
                ->removeFromSession($icon[0]);
        }
    }

    public function getIcon()
    {
        $icon = json_decode($this->icon);
        return FileManager::getInstance()->getStorageUrl() . (!empty($icon[0]) ? $icon[0] : 'no_image.jpg');
    }
}